

export const PROJECT_DESCRIPTION = [
    { id: 1, title: 'Gowork News', image: '/gowork_news.webp', description: 'Wordpress based project of a corporate news site for a big employment agency.', projectDetails: ["Detail 1a", "Detail 2a" , "Detail 3a", "Detail 3a", "Detail 3a", "Detail 3a"] },
    { id: 2, title: 'Gowork Blog', image: '/gowork_blog.webp', description: 'Refreshed old design of a Wordpress app with maintaining the same ', projectDetails: ["Detail 1b", "Detail 2b" , "Detail 3b"] },
    { id: 3, title: 'My portfolio v 1.0', image: '/portfolio_first.webp', description: 'My first ever portfolio page. It is a combination of dependencies. It is also my first attempt in TypeScript', projectDetails: ["Detail 1c", "Detail 2c" , "Detail 3c"] },
    { id: 4, title: 'My Portfolio v 2.0', image: '/portfolio_second.webp', description: 'Second portfolio that you actually look at. The goal was to create clean and simple design mixed with a powerful backend and fronend frameworks', projectDetails: ["Detail 1d", "Detail 2d" , "Detail 3d"] },
    ];



  export const ABOUT_ME = [
    {
        aboutmetext: 'W Ministerstwie Rodziny i Polityki Społecznej trwają prace nad projektem nowelizacji ustawy o pomocy społecznej. ontrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC, making it over 2000 years old. Richard McClintock, a Latin professor at Hampden-Sydney College in Virginia, looked up one of the more obscure Latin words, consectetur, from a Lorem Ipsum passage, and going through the cites of the word in classical literature, discovered the undoubtable source. ontrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC, making it over 2000 years old. Richard McClintock, a Latin professor at Hampden-Sydney College in Virginia, looked up one of the more obscure Latin words, consectetur, from a Lorem Ipsum passage, and going through the cites of the word in classical literature, discovered the undoubtable source. ontrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC, making it over 2000 years old. Richard McClintock, a Latin professor at Hampden-Sydney College in Virginia, looked up one of the more obscure Latin words, consectetur, from a Lorem Ipsum passage, and going through the cites of the word in classical literature, discovered the undoubtable source. ontrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC, making it over 2000 years old. Richard McClintock, a Latin professor at Hampden-Sydney College in Virginia, looked up one of the more obscure Latin words, consectetur, from a Lorem Ipsum passage, and going through the cites of the word in classical literature, discovered the undoubtable source. ontrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC, making it over 2000 years old. Richard McClintock, a Latin professor at Hampden-Sydney College in Virginia, looked up one of the more obscure Latin words, consectetur, from a Lorem Ipsum passage, and going through the cites of the word in classical literature, discovered the undoubtable source. '     
    },
  ];